
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author c3
 */
public class CreateAccount extends javax.swing.JFrame {

    private final JFrame previous;

    /**
     * Creates new form createAccount
     */
    public CreateAccount(javax.swing.JFrame temp) {
        initComponents();
        previous = temp;
        int size = Bank.getBankAccountList().size();
        if (size != 0) {
            textField1.setText(Bank.getBankAccountList().get(size - 1).getAccountNumber() + 1 + "");
        } else {
            textField1.setText("1");
        }
        textField1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Account");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setText("Account number");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 112, 240, 60));

        label2.setText("Name");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 180, 70));

        label3.setText("Initial Balance");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 140, 70));
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 190, 60));
        getContentPane().add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 190, 50));
        getContentPane().add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 230, 60));

        button1.setLabel("Create");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 340, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        int accountNumber = Integer.parseInt(textField1.getText());
        String name = textField2.getText();
        float amount = Float.parseFloat(textField3.getText());
        
        BankAccount bankAccount = new BankAccount(accountNumber, name, amount);
        Bank.getBankAccountList().add(bankAccount);System.out.println(Bank.getBankAccountList().size());
        
        previous.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        previous.setVisible(true);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    // End of variables declaration//GEN-END:variables
}
