
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author c3
 */
public class LoadAccount extends javax.swing.JFrame {

    private final JFrame previous;

    /**
     * Creates new form LoadAccount
     */
    public LoadAccount(javax.swing.JFrame temp) {
        initComponents();
        previous = temp;
        displayDetails(false);
        textField1.setText("0");
        jLabel1.setVisible(false);
        textField2.setEditable(false);
        textField3.setEditable(false);
        textField4.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        button1 = new java.awt.Button();
        label2 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label3 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        label4 = new java.awt.Label();
        textField4 = new java.awt.TextField();
        button2 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setText("Enter Account no.");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 190, 70));
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 70, 360, 60));

        button1.setLabel("Load");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 500, 90));

        label2.setText("Account Number");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 180, 60));

        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        getContentPane().add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 250, 60));

        label3.setText("Name");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 170, 50));
        getContentPane().add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 270, 60));

        label4.setText("Balance");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 210, 60));
        getContentPane().add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 310, 70));

        button2.setLabel("close");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 670, 110, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 420, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        BankAccount temp;
        try {
            temp = Bank.findAccount(Integer.parseInt(textField1.getText()));
            textField2.setText(temp.getAccountNumber() + "");
            textField3.setText(temp.getName() + "");
            textField4.setText(temp.getBalance() + "");
            displayDetails(true);
            jLabel1.setVisible(false);
        } catch (BankingException msg) {
            jLabel1.setVisible(true);
            jLabel1.setText(msg.message);
            displayDetails(false);
        }
       
        
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        previous.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button2ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed
    private void displayDetails(Boolean flag) {
        label2.setVisible(flag);
        label3.setVisible(flag);
        label4.setVisible(flag);
        textField2.setVisible(flag);
        textField3.setVisible(flag);
        textField4.setVisible(flag);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    // End of variables declaration//GEN-END:variables
}
